# Generated by Django 5.2.12 on 2026-04-08 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmoji',
            fields=[
                ('emoji_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('keywords', models.JSONField(default=list)),
                ('filename', models.CharField(max_length=300)),
                ('filetype', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('hide_submitted_at', models.BooleanField(default=False)),
                ('use_count', models.PositiveBigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
