# Generated by Django 5.1.4 on 2025-12-30 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aotd', '0029_album_hidden_aotduserdata_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPlayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('payload', models.JSONField()),
                ('generation_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlayback',
            fields=[
                ('aotd_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aotd.aotduserdata')),
                ('year', models.IntegerField()),
                ('payload', models.JSONField()),
                ('generation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('aotd_user', 'year')},
            },
        ),
    ]
