import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import {Providers} from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord Photo Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body className={`${inter.className} dark`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
