version: '3'
services:
  backend:
    build: ./backend
    ports: 
      - "8000:8000"
    environment:
      - APP_ENV=PROD
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  internal: {}
