# Generated by Django 5.0.6 on 2024-11-13 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_user_spotify_connected'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyUserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('country', models.CharField(max_length=2)),
                ('display_name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=256)),
                ('spotify_url', models.CharField(max_length=256)),
                ('follower_count', models.IntegerField(default=0)),
                ('user_endpoint', models.CharField(max_length=512)),
                ('spotify_id', models.CharField(max_length=256)),
                ('user_pfp_url', models.CharField(max_length=512)),
                ('user_pfp_height', models.IntegerField(null=True)),
                ('user_pfp_width', models.IntegerField(null=True)),
                ('membership_type', models.CharField(max_length=256)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
