# Generated by Django 5.0.6 on 2024-11-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0002_alter_spotifyuserdata_user_pfp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuserdata',
            name='access_token',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='spotifyuserdata',
            name='refresh_token',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='spotifyuserdata',
            name='token_expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='spotifyuserdata',
            name='token_scope',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='spotifyuserdata',
            name='token_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
