# Generated by Django 5.0.6 on 2024-11-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0004_alter_spotifyuserdata_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuserdata',
            name='token_expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
