# Generated by Django 5.0.6 on 2024-11-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0005_alter_spotifyuserdata_token_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuserdata',
            name='top_track_long_term',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spotifyuserdata',
            name='top_track_medium_term',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='spotifyuserdata',
            name='top_track_short_term',
            field=models.TextField(null=True),
        ),
    ]
