# Generated by Django 5.0.6 on 2024-11-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0006_spotifyuserdata_top_track_long_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyuserdata',
            name='top_track_medium_term',
        ),
        migrations.RemoveField(
            model_name='spotifyuserdata',
            name='top_track_short_term',
        ),
    ]
