# Generated by Django 5.0.6 on 2024-11-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0008_album_dailyalbum_review_reviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='raw_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
