# Generated by Django 5.0.6 on 2024-11-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0009_album_raw_data_album_spotify_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_comment',
        ),
    ]
