# Generated by Django 5.0.6 on 2024-11-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0010_remove_review_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
