# Generated by Django 5.1.4 on 2024-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0011_album_artist_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='first_listen',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
