# Generated by Django 5.1.4 on 2024-12-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0012_review_first_listen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewhistory',
            name='first_listen',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
