# Generated by Django 5.1.4 on 2025-01-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0013_reviewhistory_first_listen'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='aotd_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
