# Generated by Django 5.1.4 on 2025-01-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0015_reviewhistory_aotd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='aotd_date',
            field=models.DateField(),
        ),
    ]
