# Generated by Django 5.1.4 on 2025-02-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0017_alter_reviewhistory_aotd_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuserdata',
            name='selection_blocked_flag',
            field=models.BooleanField(default=False),
        ),
    ]
