# Generated by Django 5.1.4 on 2025-02-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0018_spotifyuserdata_selection_blocked_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
