# Generated by Django 5.1.4 on 2025-02-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0020_reviewhistory_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyalbum',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
