# Generated by Django 5.1.4 on 2025-03-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0022_useralbumoutage'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date_precision',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
