# Generated by Django 5.1.4 on 2025-04-07 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0023_album_release_date_album_release_date_precision'),
        ('users', '0010_user_timezone_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aotd_reviews', to='users.user'),
        ),
    ]
