# Generated by Django 5.1.4 on 2025-04-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0024_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spotifyapi.album'),
        ),
    ]
