# Generated by Django 5.1.4 on 2025-04-10 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0025_alter_dailyalbum_album'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('album', 'user', 'aotd_date')},
        ),
    ]
