# Generated by Django 5.1.4 on 2025-04-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0026_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyalbum',
            name='rating_timeline',
            field=models.JSONField(default={'timeline': []}, null=True),
        ),
        migrations.AddField(
            model_name='reviewhistory',
            name='last_updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
