# Generated by Django 5.1.4 on 2025-04-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0027_dailyalbum_rating_timeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyalbum',
            name='rating_timeline',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
