# Generated by Django 5.1.4 on 2025-04-10 22:41

import spotifyapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0028_alter_dailyalbum_rating_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyalbum',
            name='rating_timeline',
            field=models.JSONField(default=spotifyapi.models.generateTimelineDict, null=True),
        ),
    ]
