# Generated by Django 5.1.4 on 2025-04-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0030_dailyalbum_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyalbum',
            name='rating',
            field=models.FloatField(default=11.0, null=True),
        ),
    ]
