# Generated by Django 5.1.4 on 2025-04-14 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0031_alter_dailyalbum_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyuserdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='spotify_data', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserChanceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance_percentage', models.FloatField()),
                ('block_type', models.CharField(max_length=50, null=True)),
                ('reason', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('outage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotifyapi.useralbumoutage')),
                ('spotify_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aotd_chance', to='spotifyapi.spotifyuserdata')),
            ],
        ),
    ]
