# Generated by Django 5.1.4 on 2025-05-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0033_album_mbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='mbid',
        ),
    ]
