# Generated by Django 5.1.4 on 2025-05-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0034_remove_album_mbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='mbid',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
