# Generated by Django 5.1.4 on 2025-06-01 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapi', '0035_album_mbid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_aotd_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewhistory',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_history', to='spotifyapi.review'),
        ),
        migrations.AlterField(
            model_name='useralbumoutage',
            name='admin_enactor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spot_outage_admin_enactor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useralbumoutage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spot_outages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userchancecache',
            name='spotify_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spot_aotd_chance', to='spotifyapi.spotifyuserdata'),
        ),
    ]
