# Generated by Django 5.1.4 on 2025-03-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='created_at',
            new_name='creation_timestamp',
        ),
        migrations.RenameField(
            model_name='reaction',
            old_name='custom',
            new_name='custom_emoji',
        ),
    ]
