# Generated by Django 5.1.4 on 2025-12-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0003_alter_reaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(max_length=255),
        ),
    ]
