# Generated by Django 5.1.4 on 2025-05-29 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0001_initial'),
        ('spotifyapi', '0032_alter_spotifyuserdata_user_userchancecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='legacy_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_album', to='spotifyapi.album'),
        ),
    ]
