# Generated by Django 5.1.4 on 2025-05-30 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0004_alter_album_legacy_album'),
        ('spotifyapi', '0033_album_mbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='legacy_album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_album', to='spotifyapi.album'),
        ),
    ]
