# Generated by Django 5.1.4 on 2025-05-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0005_alter_album_legacy_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='disambiguation',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
