# Generated by Django 5.1.4 on 2025-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0007_alter_album_disambiguation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='disambiguation',
            field=models.CharField(default='', max_length=256),
        ),
    ]
