# Generated by Django 5.1.4 on 2025-06-01 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0008_alter_album_disambiguation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
