# Generated by Django 5.1.4 on 2025-06-01 21:46

import aotd.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0009_alter_album_submission_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('manual', models.BooleanField(default=False)),
                ('rating_timeline', models.JSONField(default=aotd.models.generateTimelineDict, null=True)),
                ('rating', models.FloatField(default=11.0, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aotd.album')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('first_listen', models.BooleanField(default=None, null=True)),
                ('aotd_date', models.DateField()),
                ('version', models.IntegerField(default=1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aotd.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aotd_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('album', 'user', 'aotd_date')},
            },
        ),
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField()),
                ('first_listen', models.BooleanField(default=None, null=True)),
                ('last_updated', models.DateTimeField(default=None, null=True)),
                ('aotd_date', models.DateField()),
                ('version', models.IntegerField(default=1)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='aotd.review')),
            ],
        ),
        migrations.CreateModel(
            name='UserAlbumOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('admin_enacted', models.BooleanField(default=False)),
                ('creation_timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('admin_enactor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outage_admin_enactor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserChanceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance_percentage', models.FloatField()),
                ('block_type', models.CharField(max_length=50, null=True)),
                ('reason', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('outage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aotd.useralbumoutage')),
                ('spotify_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aotd_chance', to='aotd.aotduserdata')),
            ],
        ),
    ]
