# Generated by Django 5.1.4 on 2025-06-01 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0010_dailyalbum_review_reviewhistory_useralbumoutage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchancecache',
            old_name='spotify_user',
            new_name='aotd_user',
        ),
    ]
