# Generated by Django 5.1.4 on 2025-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0011_rename_spotify_user_userchancecache_aotd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aotduserdata',
            name='creation_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviewhistory',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
    ]
