# Generated by Django 5.1.4 on 2025-06-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0013_alter_review_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='last_updated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviewhistory',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
    ]
