# Generated by Django 5.1.4 on 2025-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0014_alter_review_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aotduserdata',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reviewhistory',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
