# Generated by Django 5.1.4 on 2025-06-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0015_alter_aotduserdata_creation_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotduserdata',
            name='average_review_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='highest_score_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='highest_score_given',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='highest_score_mbid',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='lowest_score_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='lowest_score_given',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='lowest_score_mbid',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='review_score_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
