# Generated by Django 5.1.4 on 2025-06-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0016_aotduserdata_average_review_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aotduserdata',
            name='highest_score_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='aotduserdata',
            name='lowest_score_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='aotduserdata',
            name='total_reviews',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
