# Generated by Django 5.1.4 on 2025-06-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0017_alter_aotduserdata_highest_score_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='advancedReviewDict',
            field=models.JSONField(default=None, null=True),
        ),
    ]
