# Generated by Django 5.1.4 on 2025-06-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0018_review_advanced_review_advancedreviewdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewhistory',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewhistory',
            name='advancedReviewDict',
            field=models.JSONField(default=None, null=True),
        ),
    ]
