# Generated by Django 5.1.4 on 2025-07-11 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0019_reviewhistory_advanced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotduserdata',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='last_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aotd.album'),
        ),
    ]
