# Generated by Django 5.1.4 on 2025-07-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0020_aotduserdata_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotduserdata',
            name='first_listen_percentage',
            field=models.FloatField(default=0),
        ),
    ]
