# Generated by Django 5.1.4 on 2025-07-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0021_aotduserdata_first_listen_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotduserdata',
            name='median_review_score',
            field=models.FloatField(default=0),
        ),
    ]
