# Generated by Django 5.1.4 on 2025-07-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0022_aotduserdata_median_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyalbum',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
