# Generated by Django 5.1.4 on 2025-07-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0023_dailyalbum_admin_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotduserdata',
            name='average_selection_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='selection_score_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='total_selected',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='total_submissions',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
