# Generated by Django 5.1.4 on 2025-09-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0024_aotduserdata_average_selection_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotduserdata',
            name='review_ratio',
            field=models.FloatField(default=0),
        ),
    ]
