# Generated by Django 5.1.4 on 2025-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0025_aotduserdata_review_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotduserdata',
            name='missed_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
