# Generated by Django 5.1.4 on 2025-12-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0026_aotduserdata_missed_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyalbum',
            name='standard_deviation',
            field=models.FloatField(default=None, null=True),
        ),
    ]
