# Generated by Django 5.1.4 on 2025-12-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0027_dailyalbum_standard_deviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotduserdata',
            name='review_score_stddev',
            field=models.FloatField(default=0),
        ),
    ]
