# Generated by Django 5.1.4 on 2025-12-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0028_aotduserdata_review_score_stddev'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
