# Generated by Django 5.2.12 on 2026-03-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0030_globaltag_albumtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumtag',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
