# Generated by Django 5.2.12 on 2026-03-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0033_globaltag_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotduserdata',
            name='hide_scores_prereview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='hide_tags_prereview',
            field=models.BooleanField(default=False),
        ),
    ]
