# Generated by Django 5.2.12 on 2026-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0035_albumcommenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcommenthistory',
            name='admin_edit',
            field=models.BooleanField(default=False),
        ),
    ]
