# Generated by Django 5.2.12 on 2026-06-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0037_albumownershiphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_group_id',
            field=models.CharField(db_index=True, default=None, max_length=256, null=True),
        ),
    ]
