# Generated by Django 5.2.12 on 2026-06-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0039_backfill_release_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyalbum',
            name='rating',
            field=models.FloatField(default=11.0),
        ),
    ]
