# Generated by Django 5.2.12 on 2026-07-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0040_alter_dailyalbum_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotduserdata',
            name='review_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userchancecache',
            name='chance_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
