# Generated by Django 5.2.12 on 2026-08-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0041_aotduserdata_review_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotduserdata',
            name='review_seconds_since_midnight_average',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aotduserdata',
            name='review_seconds_since_midnight_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
