# Generated by Django 5.2.17 on 2026-09-19 18:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0042_aotduserdata_review_seconds_since_midnight_average_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sha256', models.CharField(editable=False, max_length=64, unique=True)),
                ('filename', models.CharField(editable=False, max_length=64)),
                ('filetype', models.CharField(choices=[('image/webp', 'WebP'), ('image/gif', 'GIF')], max_length=32)),
                ('size_bytes', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('source_url', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviews', models.ManyToManyField(blank=True, related_name='images', to='aotd.review')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_review_images', to='aotd.aotduserdata')),
            ],
        ),
    ]
