# Generated by Django 5.2.17 on 2026-09-24 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0043_reviewimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_viewed', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aotdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aotd.aotduserdata')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aotd.review')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='views',
            field=models.ManyToManyField(through='aotd.ReviewView', to='aotd.aotduserdata'),
        ),
        migrations.AddConstraint(
            model_name='reviewview',
            constraint=models.UniqueConstraint(fields=('aotdUser', 'review'), name='unique_review_view_group'),
        ),
    ]
