# Generated by Django 5.2.17 on 2026-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aotd', '0044_reviewview_review_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyalbum',
            name='rating',
            field=models.FloatField(default=11.0, null=True),
        ),
    ]
