# Generated by Django 5.1.4 on 2025-03-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_useraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordTokens',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('discord_access_token', models.CharField(max_length=512, null=True)),
                ('discord_token_type', models.CharField(max_length=50, null=True)),
                ('discord_expiry_date', models.DateTimeField(null=True)),
                ('discord_refresh_token', models.CharField(max_length=512, null=True)),
                ('discord_scope', models.CharField(max_length=512, null=True)),
            ],
        ),
    ]
