# Generated by Django 5.1.4 on 2025-03-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discordtokens',
            old_name='discord_access_token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='discordtokens',
            old_name='discord_expiry_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='discordtokens',
            old_name='discord_refresh_token',
            new_name='refresh_token',
        ),
        migrations.RenameField(
            model_name='discordtokens',
            old_name='discord_scope',
            new_name='scope',
        ),
        migrations.RenameField(
            model_name='discordtokens',
            old_name='discord_token_type',
            new_name='token_type',
        ),
    ]
