# Generated by Django 5.0.6 on 2024-10-21 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_user_discord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(default='No Description Provided')),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=300)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_images', to='users.user')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to='users.user')),
            ],
        ),
    ]
