# Generated by Django 5.0.6 on 2024-10-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('users', '0003_alter_user_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tagged_users',
            field=models.ManyToManyField(to='users.user'),
        ),
    ]
