# Generated by Django 5.0.6 on 2024-10-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_image_tagged_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filetype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
