# Generated by Django 5.1.4 on 2025-12-12 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image_filetype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tagged_users',
            field=models.ManyToManyField(related_name='images_tagged_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
