# Generated by Django 5.0.6 on 2024-09-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(max_length=100)),
                ('todo_description', models.CharField(max_length=2000)),
                ('todo_status', models.CharField(choices=[('BK', 'Backlog'), ('IP', 'Work In Progress'), ('DN', 'Done')], default='BK', max_length=2)),
                ('todo_category', models.CharField(choices=[('FN', 'Functionality'), ('UI', 'User Interface/User Experience'), ('CI', 'CI/CD'), ('DE', 'Data Engineering')], default='FN', max_length=2)),
            ],
        ),
    ]
