# Generated by Django 5.0.6 on 2024-09-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='TodoItem',
        ),
    ]
