# Generated by Django 5.0.6 on 2024-09-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_question_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='todo_description',
            field=models.CharField(default='No Description Provided', max_length=2000),
        ),
    ]
