# Generated by Django 5.0.6 on 2024-09-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoitem_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='todo_description',
            field=models.TextField(default='No Description Provided'),
        ),
    ]
