# Generated by Django 5.0.6 on 2024-10-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('guid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='GUID')),
                ('username', models.CharField(max_length=100)),
                ('last_updated_timestamp', models.DateTimeField(auto_now=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=254)),
                ('discord_id', models.BigIntegerField()),
                ('discord_discriminator', models.CharField(blank=True, max_length=4, null=True)),
                ('discord_is_verified', models.BooleanField(default=False)),
                ('discord_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
