# Generated by Django 5.0.6 on 2024-11-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_discord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_connected',
            field=models.BooleanField(default=False),
        ),
    ]
