# Generated by Django 5.1.4 on 2025-02-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_spotify_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
