# Generated by Django 5.1.4 on 2025-02-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_last_response_timestamp_user_last_request_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_heartbeat_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
