# Generated by Django 5.1.4 on 2025-03-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone_string',
            field=models.CharField(default='America/Chicago', max_length=255),
        ),
    ]
