# Generated by Django 5.2.12 on 2026-06-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_spotify_connected_user_aotd_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_avatar_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
